# Assignment

Q1. Write the NumPy program to create a 2d array with 6 on the border
and 0 inside?

    Expected OutputOriginal array-
    [ [6 6 6 6 6]
     [ 6 6 6 6 6]
     [ 6 6 6 6 6 ]
    [ 6 6 6 6 6 ]
    [ 6 6 6 6 ] ].
    6 on the border and 0 inside in the array-
    [[ 6 6 6 6 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 6 6 6 6]].

In [7]:
import numpy as np
#n = np.empty((5, 5))
n = np.full((5,5),6)
print('Original array:',n)
n[1:-1,1:-1] = 0
print('Output:',n)

Original array: [[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]
Output: [[6 6 6 6 6]
 [6 0 0 0 6]
 [6 0 0 0 6]
 [6 0 0 0 6]
 [6 6 6 6 6]]


Q2. Write the NumPy program to create a 8x8 matrix and fill it with the
checkerboard pattern?
    
    Checkerboard pattern-
    [[3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]].

In [8]:
import numpy as np
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.full((8,8),3,dtype=int)
x[1::2,::2] = 9
x[::2,1::2] = 9
print(x)

Checkerboard pattern:
[[3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]]


Q3. Write the NumPy program to create an empty and a full array.
 
     Expected Output-
    [[4.45057637e-308 1.78021527e-306 8.45549797e-307 1.37962049e-306]
    [1.11260619e-306 1.78010255e-306 9.79054228e-307 4.45057637e-308]
    [8.45596650e-307 9.34602321e-307 4.94065646e-322 0.00000000e+000]]
    [[6 6 6]
    [6 6 6]
    [6 6 6]]


In [9]:
import numpy as np
y = np.empty((3, 4))
print(y)
x = np.full((3,3),6)
print(x)

[[1.12738944e-311 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [2.37094091e+077 2.44598767e-056 1.66023197e-076 7.91844959e+165]
 [3.83856783e+175 7.18834827e-067 4.08778879e-037 1.17606805e-047]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]


Q4. Write the NumPy program to convert the values of Centigrade
degrees into the Fahrenheit degrees and the centigrade values are
stored in the NumPy array.
    
    Sample Array -[0, 12, 45.21 ,34, 99.91]
    Expected OutputValues in Fahrenheit degrees-
    [ 0. 12. 45.21 34. 99.91]
    Values in Centigrade degrees-
    [-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778]

In [10]:
import numpy as np
fvalues = [0, 12, 45.21, 34, 99.91]
F = np.array(fvalues)
print("Values in Fahrenheit degrees:")
print(F)
print("Values in  Centigrade degrees:") 
print(5*F/9 - 5*32/9)

Values in Fahrenheit degrees:
[ 0.   12.   45.21 34.   99.91]
Values in  Centigrade degrees:
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


Q5. Write the NumPy program to find the real and imaginary parts of an
array of complex numbers?

    Expected OutputOriginal array [ 1.00000000+0.j 0.70710678+0.70710678j]
    Real part of the array-
    [ 1. 0.70710678]
    Imaginary part of the array-
    [ 0. 0.70710678]

In [11]:
import numpy as np
x = np.sqrt([1+0j,0+1j ])
print("Original array:x ",x)
print("Real part of the array:")
print(x.real)
print("Imaginary part of the array:")
print(x.imag)

Original array:x  [1.        +0.j         0.70710678+0.70710678j]
Real part of the array:
[1.         0.70710678]
Imaginary part of the array:
[0.         0.70710678]


Q6. Write the NumPy program to test whether each element of a 1-D
array is also present in the second array?

    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [0, 40]
    Compare each element of array1 and array2
    [ True False False True False]


In [12]:
a = np.array([0,10,20,40,60])
b = np.array([0,40])        
np.in1d(a,b)

array([ True, False, False,  True, False])

Q7. Write the NumPy program to find common values between two
arrays?
    
    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [10, 30, 40]
    Common values between two arrays-
    [10 40]

In [13]:
a = np.array([0,10,20,40,60])
b = np.array([10,30,40])
# function  used to check whether each element of a 1-D array is also present in a second array.
print('Common values between a and b is: ',np.intersect1d(a,b))

Common values between a and b is:  [10 40]


Q8. Write the NumPy program to get the unique elements of an array?

    Expected OutputOriginal array-
    [10 10 20 20 30 30]
    Unique elements of the above array-
    [10 20 30]
    P a g e 14 | 44
    Original array-
    [[1 1]
    [2 3]]
    Unique elements of the above array-
    [1 2 3]

In [14]:
a = np.array([10, 10, 20, 20, 30, 30])
i = np.unique(a)
i


array([10, 20, 30])

In [17]:
b = np.array([[1, 1],
[2, 3]])
i = np.unique(b)
i

array([1, 2, 3])

Q9. Write the NumPy program to find the set exclusive-or of two arrays.
Set exclusive-or will return the sorted, unique values that are in
only one (not both) of the input arrays?

    Array1- [ 0 10 20 40 60 80]
    Array2- [10, 30, 40, 50, 70]
    Unique values that are in only one (not both) of the input arrays-
    [ 0 20 30 50 60 70 80]

In [19]:
Array1= np.array([0, 10, 20, 40, 60, 80])
Array2= np.array([10, 30, 40, 50, 70])

#find common values between 2 arrays
it = Array1[np.in1d(Array1,Array2)]

#concatenate both arrays
con = np.unique(np.concatenate((Array1,Array2), axis=0))

#Find the set difference of two arrays.
#Return the unique values in Array1 that are not in Array2.
z = np.setdiff1d(con,it)
z

array([ 0, 20, 30, 50, 60, 70, 80])

Q10. Write the NumPy program to test if all elements in an array
evaluate to True ?
 
Note: 0 evaluates to False in NumPy

In [20]:
print(np.all([[True,False],[True,True]])) # return false because of one of the value is False
print(np.all([1,2,3,4])) # return true because all are numbers
print(np.all([0,2,3,4])) # return False becuase one of the value is 0

False
True
False


Q11. Write the NumPy program to test whether any array element along
the given axis evaluates to True?
 
Note: 0 evaluates to False in NumPy

In [21]:
# return True if one of the element of a evaluate to True
print(np.any([[True,False],[True,True]])) 
print(np.any([1,2,3,4])) 
print(np.any([0,2,3,4])) 

True
True
True


Q12. Write the NumPy program to construct an array by repeating?

    Sample array- [1, 2, 3, 4]
    Expected OutputOriginal array
    [1, 2, 3, 4]
    Repeating 2 times
    [1 2 3 4 1 2 3 4]
    Repeating 3 times
    [1 2 3 4 1 2 3 4 1 2 3 4]

In [22]:
# based on 2nd parameter, the numbers will repeat
np.tile([1,2,3,4], 2)

array([1, 2, 3, 4, 1, 2, 3, 4])

In [23]:
# based on 2nd parameter, the numbers will repeat
np.tile([1,2,3,4], 3)

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

Q13. Write the NumPy program to find the indices of the maximum and
minimum values with the given axis of an array?

    Original array- [1 2 3 4 5 6]
    Maximum Values- 5
    Minimum Values- 0

In [24]:
a = np.array([1,2,3,4,5,6])
print('Index of max value:',np.argmax(a,axis=0))
print('Index of min value:',np.argmin(a,axis=0))

Index of max value: 5
Index of min value: 0


Q14. Write the NumPy program compare two arrays using numpy?

    Array a- [1 2]
    Array b- [4 5]
    a > b
    [False False]
    a >= b
    [False False]
    a < b
    [ True True]
    a <= b
    [ True True]


In [25]:
a = np.array([1,2])
b = np.array([4,5])
print(a>b)
print(a>=b)
print(a<b)
print(a<=b)

[False False]
[False False]
[ True  True]
[ True  True]


Q15. Write the NumPy program to sort an along the first, last axis of an
array?

    Sample array- [[2,5],[4,4]]
    Expected OutputOriginal array:
    [[4 6]
    [2 1]]
    Sort along the first axis:
    [[2 1]
    [4 6]]
    Sort along the last axis-
    [[1 2]
    [4 6]]

In [26]:
import numpy as np
arr = np.array([[4, 6],[2, 1]])
print('Original array: ')
print(arr)
print('Sort along the first axis: ')
x = np.sort(arr, axis=0)
print(x)
print("Sort along the last axis: ")
y = np.sort(x, axis=1)
print(y)

Original array: 
[[4 6]
 [2 1]]
Sort along the first axis: 
[[2 1]
 [4 6]]
Sort along the last axis: 
[[1 2]
 [4 6]]


Q16. Write the NumPy program to sort pairs of first name and last name
return their indices (first by last name, then by first name).

    first_names - ( Betsey, Shelley, Lanell, Genesis, Margery )
    last_names - ( Battle, Brien, Plotner, Stahl, Woolum )
    Expected Output-
    [1 3 2 4 0]

In [27]:
import numpy as np
first_names =    ('Betsey', 'Shelley', 'Lanell', 'Genesis','Margery')
last_names = ('Battle', 'Brien',  'Plotner', 'Stahl','Woolum')
x = np.lexsort((first_names, last_names))
print(x)

[0 1 2 3 4]


Q17. Write the NumPy program to get the values and indices of the
elements that are bigger than 10 in the given array?

    Original array-
    [[ 0 10 20]
    [20 30 40]]
    Values bigger than 10 = [20 20 30 40]
    Their indices are (array([0, 1, 1, 1]), array([2, 0, 1, 2]))

In [28]:
org= np.array([[0, 10, 20], [20, 30, 40]])
# show array value greater than 10
a = org[org >10]
a

array([20, 20, 30, 40])

Q18. Write the NumPy program to find the memory size of a NumPy
array?

    Expected Output128 bytes


In [29]:
import numpy as np
#array filled with zero
zz = np.zeros((4,4))
zz
print('size of zz array in bytes:',zz.nbytes)

size of zz array in bytes: 128


## Great Job!